
import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <div className="py-32 relative overflow-hidden" id="disclaimer">
      <div className="absolute inset-0 bg-gradient-to-br from-purple-900/20 via-blue-900/10 to-cyan-900/20"></div>
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(147,51,234,0.1)_0%,transparent_50%)]"></div>
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_bottom,rgba(6,182,212,0.1)_0%,transparent_50%)]"></div>
      
      <div className="container mx-auto px-6 relative z-10">
        <div className="text-center mb-20">
          <h2 className="text-5xl md:text-6xl font-bold mb-8 bg-gradient-to-r from-purple-300 via-cyan-300 to-purple-300 bg-clip-text text-transparent animate-glow">
            Legal Disclaimer
          </h2>
          <div className="w-32 h-1 bg-gradient-to-r from-purple-500 via-cyan-400 to-purple-500 mx-auto rounded-full shadow-[0_0_20px_rgba(147,51,234,0.6)]"></div>
        </div>

        <div className="max-w-6xl mx-auto backdrop-blur-xl bg-gradient-to-br from-purple-500/10 via-blue-500/5 to-cyan-500/10 border border-purple-300/20 rounded-3xl p-12 shadow-[0_20px_60px_rgba(147,51,234,0.3)] hover:shadow-[0_25px_80px_rgba(6,182,212,0.4)] transition-all duration-700">
          
          <div className="mb-12 p-8 rounded-2xl bg-gradient-to-r from-cyan-500/10 to-purple-500/10 border border-cyan-300/20">
            <h3 className="text-2xl font-bold mb-6 bg-gradient-to-r from-cyan-300 to-purple-300 bg-clip-text text-transparent">
              Usage Policy
            </h3>
            <p className="text-white/90 mb-6 text-lg leading-relaxed">
              Product Photography Designer GPT is provided as a tool to assist in creating product advertising visuals. AI WEB TOOLS LLC does not guarantee specific outcomes or results from using the service. The quality and usability of generated images depend on various factors including the quality of input images, clarity of instructions, and specific use-case requirements.
            </p>
          </div>

          <div className="mb-12 p-8 rounded-2xl bg-gradient-to-r from-purple-500/10 to-cyan-500/10 border border-purple-300/20">
            <h3 className="text-2xl font-bold mb-6 bg-gradient-to-r from-purple-300 to-cyan-300 bg-clip-text text-transparent">
              Image Ownership & Rights
            </h3>
            <p className="text-white/90 mb-6 text-lg leading-relaxed">
              Users retain full ownership of their original uploaded product images. Images generated by Product Photography Designer GPT are provided for the user's commercial use. AI WEB TOOLS LLC does not claim ownership of generated images. However, users are responsible for ensuring they have proper rights to the products depicted in uploaded images.
            </p>
          </div>

          <div className="mb-12 p-8 rounded-2xl bg-gradient-to-r from-cyan-500/10 to-purple-500/10 border border-cyan-300/20">
            <h3 className="text-2xl font-bold mb-6 bg-gradient-to-r from-cyan-300 to-purple-300 bg-clip-text text-transparent">
              Prohibited Content
            </h3>
            <p className="text-white/90 mb-6 text-lg leading-relaxed">
              Users agree not to upload images or request generated content that:
            </p>
            <ul className="list-none space-y-3 text-white/90 mb-6 text-lg">
              <li className="flex items-center">
                <div className="w-2 h-2 bg-gradient-to-r from-purple-400 to-cyan-400 rounded-full mr-4 shadow-[0_0_10px_rgba(147,51,234,0.6)]"></div>
                Contains illegal products or services
              </li>
              <li className="flex items-center">
                <div className="w-2 h-2 bg-gradient-to-r from-cyan-400 to-purple-400 rounded-full mr-4 shadow-[0_0_10px_rgba(6,182,212,0.6)]"></div>
                Violates intellectual property rights
              </li>
              <li className="flex items-center">
                <div className="w-2 h-2 bg-gradient-to-r from-purple-400 to-cyan-400 rounded-full mr-4 shadow-[0_0_10px_rgba(147,51,234,0.6)]"></div>
                Contains adult content, violence, or harmful material
              </li>
              <li className="flex items-center">
                <div className="w-2 h-2 bg-gradient-to-r from-cyan-400 to-purple-400 rounded-full mr-4 shadow-[0_0_10px_rgba(6,182,212,0.6)]"></div>
                Depicts individuals without their consent
              </li>
              <li className="flex items-center">
                <div className="w-2 h-2 bg-gradient-to-r from-purple-400 to-cyan-400 rounded-full mr-4 shadow-[0_0_10px_rgba(147,51,234,0.6)]"></div>
                Promotes misinformation or deception
              </li>
            </ul>
            <p className="text-white/90 text-lg leading-relaxed">
              AI WEB TOOLS LLC reserves the right to refuse service for any content deemed inappropriate or in violation of these terms.
            </p>
          </div>

          <div className="mb-12 p-8 rounded-2xl bg-gradient-to-r from-purple-500/10 to-cyan-500/10 border border-purple-300/20">
            <h3 className="text-2xl font-bold mb-6 bg-gradient-to-r from-purple-300 to-cyan-300 bg-clip-text text-transparent">
              Limitation of Liability
            </h3>
            <p className="text-white/90 text-lg leading-relaxed">
              AI WEB TOOLS LLC and its affiliates shall not be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the service; (ii) any conduct or content of any third party on the service; (iii) any content obtained from the service; and (iv) unauthorized access, use or alteration of your transmissions or content.
            </p>
          </div>

          <div className="mb-12 p-8 rounded-2xl bg-gradient-to-r from-cyan-500/10 to-purple-500/10 border border-cyan-300/20">
            <h3 className="text-2xl font-bold mb-6 bg-gradient-to-r from-cyan-300 to-purple-300 bg-clip-text text-transparent">
              Third-Party Services
            </h3>
            <p className="text-white/90 text-lg leading-relaxed">
              Product Photography Designer GPT utilizes OpenAI's GPT-4o technology. Usage is subject to OpenAI's terms of service and policies. AI WEB TOOLS LLC is not responsible for changes, interruptions, or discontinuation of third-party services that may affect our tool's functionality.
            </p>
          </div>

          <div className="p-8 rounded-2xl bg-gradient-to-r from-purple-500/10 to-cyan-500/10 border border-purple-300/20">
            <h3 className="text-2xl font-bold mb-6 bg-gradient-to-r from-purple-300 to-cyan-300 bg-clip-text text-transparent">
              Modifications to Service
            </h3>
            <p className="text-white/90 text-lg leading-relaxed">
              AI WEB TOOLS LLC reserves the right to modify or discontinue, temporarily or permanently, the service with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the service.
            </p>
          </div>
        </div>
        
        {/* Educational disclaimer highlight */}
        <div className="mt-16 text-center">
          <div className="inline-block p-8 rounded-3xl bg-gradient-to-r from-purple-500/20 to-cyan-500/20 border border-purple-300/30 backdrop-blur-md shadow-[0_20px_60px_rgba(147,51,234,0.4)]">
            <p className="text-white/95 text-xl font-bold bg-gradient-to-r from-purple-200 to-cyan-200 bg-clip-text text-transparent">
              For informational, educational, and research purposes only.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
