
import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <div className="py-24 relative bg-cyber-dark" id="disclaimer">
      <div className="absolute inset-0 cyber-grid opacity-10"></div>
      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-6">
            <span className="neon-text-purple">Legal </span>
            <span className="neon-text-teal">Disclaimer</span>
          </h2>
        </div>

        <div className="max-w-4xl mx-auto glass-panel p-8">
          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-3 neon-text-teal">Usage Policy</h3>
            <p className="text-cyber-text/80 mb-4">
              Product Photography Designer GPT is provided as a tool to assist in creating product advertising visuals. AI WEB TOOLS LLC does not guarantee specific outcomes or results from using the service. The quality and usability of generated images depend on various factors including the quality of input images, clarity of instructions, and specific use-case requirements.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-3 neon-text-teal">Image Ownership & Rights</h3>
            <p className="text-cyber-text/80 mb-4">
              Users retain full ownership of their original uploaded product images. Images generated by Product Photography Designer GPT are provided for the user's commercial use. AI WEB TOOLS LLC does not claim ownership of generated images. However, users are responsible for ensuring they have proper rights to the products depicted in uploaded images.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-3 neon-text-teal">Prohibited Content</h3>
            <p className="text-cyber-text/80 mb-4">
              Users agree not to upload images or request generated content that:
            </p>
            <ul className="list-disc pl-6 text-cyber-text/80 mb-4">
              <li>Contains illegal products or services</li>
              <li>Violates intellectual property rights</li>
              <li>Contains adult content, violence, or harmful material</li>
              <li>Depicts individuals without their consent</li>
              <li>Promotes misinformation or deception</li>
            </ul>
            <p className="text-cyber-text/80 mb-4">
              AI WEB TOOLS LLC reserves the right to refuse service for any content deemed inappropriate or in violation of these terms.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-3 neon-text-teal">Limitation of Liability</h3>
            <p className="text-cyber-text/80 mb-4">
              AI WEB TOOLS LLC and its affiliates shall not be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the service; (ii) any conduct or content of any third party on the service; (iii) any content obtained from the service; and (iv) unauthorized access, use or alteration of your transmissions or content.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold mb-3 neon-text-teal">Third-Party Services</h3>
            <p className="text-cyber-text/80 mb-4">
              Product Photography Designer GPT utilizes OpenAI's GPT-4o technology. Usage is subject to OpenAI's terms of service and policies. AI WEB TOOLS LLC is not responsible for changes, interruptions, or discontinuation of third-party services that may affect our tool's functionality.
            </p>
          </div>

          <div>
            <h3 className="text-xl font-semibold mb-3 neon-text-teal">Modifications to Service</h3>
            <p className="text-cyber-text/80">
              AI WEB TOOLS LLC reserves the right to modify or discontinue, temporarily or permanently, the service with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the service.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
